In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Cars_dataset.csv')

In [3]:
df.head()

Name  Miles_per_Gallon  Cylinders  Displacement  \
0  chevrolet chevelle malibu              18.0          8         307.0   
1          buick skylark 320              15.0          8         350.0   
2         plymouth satellite              18.0          8         318.0   
3              amc rebel sst              16.0          8         304.0   
4                ford torino              17.0          8         302.0   

   Horsepower  Weight_in_lbs  Acceleration      Year Origin  
0       130.0           3504          12.0  1/1/1970    USA  
1       165.0           3693          11.5  1/1/1970    USA  
2       150.0           3436          11.0  1/1/1970    USA  
3       150.0           3433          12.0  1/1/1970    USA  
4       140.0           3449          10.5  1/1/1970    USA

In [4]:
df.shape

(406, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Name              406 non-null    object 
 1   Miles_per_Gallon  398 non-null    float64
 2   Cylinders         406 non-null    int64  
 3   Displacement      406 non-null    float64
 4   Horsepower        400 non-null    float64
 5   Weight_in_lbs     406 non-null    int64  
 6   Acceleration      406 non-null    float64
 7   Year              406 non-null    object 
 8   Origin            406 non-null    object 
dtypes: float64(4), int64(2), object(3)
memory usage: 28.7+ KB


In [6]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
l[9]

9

In [8]:
l2=[str(c) for c in l]

In [9]:
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
l3=[True,3,"2",2.2,"rama"]
[type(i) for i in l3 ]

[bool, int, str, float, str]

In [11]:
import array

In [12]:
np.array([0,1,2,3,4,5,6,7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
l1=list(range(10))
l2=np.array(l1)
l2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
l1=list(range(10))
l1=[str(i) for i in l1]
l2=np.array(l1,dtype="int")
l2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
l1=list(range(10))
l2=np.array(l1 ,dtype="float")
l2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
l1=list(range(10))
l1[9]="10"
l1=[type(i) for i in l1]
l2=np.array(l1)
l2

array([<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>, <class 'str'>], dtype=object)

In [17]:
re=[1,6,11]
np.array([range(i,i+5)for i in re])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
np.ones((3,5),dtype="str")

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.full((2,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.random.random((3,5))

array([[0.28981513, 0.25098739, 0.24556765, 0.80428935, 0.18520261],
       [0.33762206, 0.06901975, 0.77157848, 0.57480081, 0.22901818],
       [0.15674819, 0.46740108, 0.97030812, 0.24837007, 0.94264024]])

In [25]:
np.random.normal(0,1,(2,3))

array([[-1.31922194,  1.81190828, -1.0456844 ],
       [-0.06886212, -0.45232063,  0.56382648]])

In [26]:
np.random.randint(1,5,(3,2))

array([[2, 2],
       [3, 4],
       [3, 1]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.empty(2)

array([2.12199579e-314, 6.36598737e-314])

In [29]:
np.zeros(4,dtype="complex_")

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [30]:
np.zeros(4,dtype=np.bool)

array([False, False, False, False])

In [31]:
x1=np.random.randint(2,size=(2))
x2=np.random.randint(5,size=(2,3))
x3=np.random.randint(10,size=(2,3,5))

In [32]:
print(x1)
print(x2)
print(x3)

[0 1]
[[4 1 2]
 [1 2 2]]
[[[4 4 5 2 7]
  [6 1 8 9 6]
  [3 5 5 6 2]]

 [[9 5 8 6 4]
  [9 7 9 9 7]
  [6 7 5 1 2]]]


In [33]:
print("diamention of x3:",x3.ndim)
print("size of x3:",x3.size)
print("shape of x3:",x3.shape)


diamention of x3: 3
size of x3: 30
shape of x3: (2, 3, 5)


In [34]:
x1.dtype

dtype('int32')

In [35]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")


itemsize: 4 bytes
nbytes: 120 bytes


In [36]:
l=np.array(range(1,11))
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
l[1]

2

In [38]:
l[-2]

9

In [39]:
x=np.random.randint(10,size=(3,3,4))
x

array([[[7, 0, 5, 8],
        [9, 8, 2, 0],
        [1, 0, 6, 8]],

       [[4, 0, 9, 1],
        [2, 2, 5, 7],
        [3, 2, 9, 5]],

       [[9, 4, 8, 5],
        [1, 4, 2, 5],
        [6, 3, 5, 7]]])

In [40]:
x[1]

array([[4, 0, 9, 1],
       [2, 2, 5, 7],
       [3, 2, 9, 5]])

In [41]:
x[1,2]

array([3, 2, 9, 5])

In [42]:
x[1,-1,-1]

5

In [43]:
x2=np.random.randint(5,size=(4,3))
x2

array([[0, 1, 3],
       [1, 4, 3],
       [4, 1, 0],
       [2, 1, 1]])

In [44]:
x2[:3,:2]

array([[0, 1],
       [1, 4],
       [4, 1]])

In [45]:
x2[:2,:2]

array([[0, 1],
       [1, 4]])

In [46]:
x

array([[[7, 0, 5, 8],
        [9, 8, 2, 0],
        [1, 0, 6, 8]],

       [[4, 0, 9, 1],
        [2, 2, 5, 7],
        [3, 2, 9, 5]],

       [[9, 4, 8, 5],
        [1, 4, 2, 5],
        [6, 3, 5, 7]]])

In [47]:
x[:1,::3]

array([[[7, 0, 5, 8]]])

In [48]:
x[1::2]

array([[[4, 0, 9, 1],
        [2, 2, 5, 7],
        [3, 2, 9, 5]]])

In [49]:
x[2,1:3,2:5]

array([[2, 5],
       [5, 7]])

In [50]:
x[0,0]

array([7, 0, 5, 8])

In [51]:
l=np.array(range(1,11))
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
l[5:]

array([ 6,  7,  8,  9, 10])

In [53]:
l[2:5]

array([3, 4, 5])

In [54]:
l[1:8:2]

array([2, 4, 6, 8])

In [55]:
l_copy=l.copy()
l_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
l_copy[0]=99
l_copy

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
p=l.reshape((2,5))

In [59]:
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
p.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [61]:
p[np.newaxis,:]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [62]:
x=np.arange(1,10,2)
y=np.array([11 , 12])
z=np.arange(15,20)
print(x)
print(y)
print(z)

[1 3 5 7 9]
[11 12]
[15 16 17 18 19]


In [63]:
new=np.concatenate([x,y,z])
new

array([ 1,  3,  5,  7,  9, 11, 12, 15, 16, 17, 18, 19])

In [64]:
n=new.reshape(4,3)
n

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [12, 15, 16],
       [17, 18, 19]])

In [65]:
x2=np.random.randint(5,size=(4,3))
x2

array([[3, 2, 2],
       [0, 3, 2],
       [1, 3, 4],
       [3, 2, 0]])

In [66]:
np.vstack([x2,n])

array([[ 3,  2,  2],
       [ 0,  3,  2],
       [ 1,  3,  4],
       [ 3,  2,  0],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [12, 15, 16],
       [17, 18, 19]])

In [67]:
c=np.hstack([x2,n])
c

array([[ 3,  2,  2,  1,  3,  5],
       [ 0,  3,  2,  7,  9, 11],
       [ 1,  3,  4, 12, 15, 16],
       [ 3,  2,  0, 17, 18, 19]])

In [68]:
x,y,z=np.split(c,[1,3])

print(x)
print(y)
print(z)

[[3 2 2 1 3 5]]
[[ 0  3  2  7  9 11]
 [ 1  3  4 12 15 16]]
[[ 3  2  0 17 18 19]]


In [69]:
upper,lower=np.vsplit(c,[2])
print(upper)
print(lower)

[[ 3  2  2  1  3  5]
 [ 0  3  2  7  9 11]]
[[ 1  3  4 12 15 16]
 [ 3  2  0 17 18 19]]


In [70]:
left,right=np.hsplit(c,[3])
print(left)
print(right)

[[3 2 2]
 [0 3 2]
 [1 3 4]
 [3 2 0]]
[[ 1  3  5]
 [ 7  9 11]
 [12 15 16]
 [17 18 19]]


In [71]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [72]:
np.add(x,4)

array([4, 5, 6, 7])

In [73]:
new1=np.subtract(x,2)
new1

array([-2, -1,  0,  1])

In [74]:
np.negative(x)

array([ 0, -1, -2, -3])

In [75]:
np.multiply(x,2)

array([0, 2, 4, 6])

In [76]:
np.divide(x,2)

array([0. , 0.5, 1. , 1.5])

In [77]:
np.floor_divide(x,3)

array([0, 0, 0, 1], dtype=int32)

In [78]:
np.power(x,6)

array([  0,   1,  64, 729], dtype=int32)

In [79]:
np.mod(x,3)

array([0, 1, 2, 0], dtype=int32)

In [80]:
new1

array([-2, -1,  0,  1])

In [81]:
np.abs(new1)

array([2, 1, 0, 1])

In [82]:
np.absolute(new1)

array([2, 1, 0, 1])

In [83]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [84]:
x=np.array([-1,0,1])
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [85]:
x = [1, 2, 3]

print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [86]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [87]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [88]:
from scipy import special

x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))


gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [89]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [90]:
y=np.empty(6)
y

array([0., 0., 0., 0., 0., 0.])

In [91]:
 x = np.arange(5)
 y = np.empty(5)
 np.multiply(x, 10, out=y)
 print(y)

[ 0. 10. 20. 30. 40.]


In [92]:
 y = np.zeros(10)
 np.power(2, x, out=y[::2])
 print(y)


[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [93]:
x = np.arange(1, 10)
print(x)
print("multiplicaton :",np.multiply.reduce(x))
print("Addition :",np.add.reduce(x))
print("add accumulate",np.add.accumulate(x))
print("multi accumulate",np.multiply.accumulate(x))
print(np.add.outer(x, x))

[1 2 3 4 5 6 7 8 9]
multiplicaton : 362880
Addition : 45
add accumulate [ 1  3  6 10 15 21 28 36 45]
multi accumulate [     1      2      6     24    120    720   5040  40320 362880]
[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]


In [94]:
 big_array = np.random.rand(1000000)
 %timeit sum(big_array)
 %timeit np.sum(big_array)


369 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.84 ms ± 92.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [95]:
x=np.concatenate([np.arange(2,10,2),np.arange(2,10,2)])
np.sum(x)

40

In [96]:
x

array([2, 4, 6, 8, 2, 4, 6, 8])

In [97]:
n=np.arange(1,21)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
sum(n)

210

In [99]:
np.sum(n)

210

In [100]:
%timeit sum(n)
%timeit np.sum(n)

9.42 µs ± 946 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
9.94 µs ± 1.39 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [101]:
min(n)

1

In [102]:
max(n)

20

In [103]:
print(n.min(),n.max(), n.sum())


1 20 210


In [104]:
c=np.random.randint(1,3,(3,3))
c

array([[1, 1, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [105]:
c.sum()

14

In [106]:
c.min(axis=0)

array([1, 1, 1])

In [107]:
c.max(axis=0)

array([2, 2, 2])

In [108]:
np.prod(c)

32

In [109]:
np.mean(c)

1.5555555555555556

In [110]:
np.std(c)

0.4969039949999533

In [111]:
np.var(c)

0.2469135802469136

In [112]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
np.argmin(n)

0

In [114]:
np.argmax(n)

19

In [115]:
np.median(n)

10.5

In [116]:
np.any(n)

True

In [117]:
np.all(n)

True

In [118]:
df=pd.read_csv('Cars_dataset.csv')
df.head()

Name  Miles_per_Gallon  Cylinders  Displacement  \
0  chevrolet chevelle malibu              18.0          8         307.0   
1          buick skylark 320              15.0          8         350.0   
2         plymouth satellite              18.0          8         318.0   
3              amc rebel sst              16.0          8         304.0   
4                ford torino              17.0          8         302.0   

   Horsepower  Weight_in_lbs  Acceleration      Year Origin  
0       130.0           3504          12.0  1/1/1970    USA  
1       165.0           3693          11.5  1/1/1970    USA  
2       150.0           3436          11.0  1/1/1970    USA  
3       150.0           3433          12.0  1/1/1970    USA  
4       140.0           3449          10.5  1/1/1970    USA

In [119]:
horsepower=np.array([df.Horsepower])
horsepower

array([[130., 165., 150., 150., 140., 198., 220., 215., 225., 190., 115.,
        165., 153., 175., 175., 170., 160., 140., 150., 225.,  95.,  95.,
         97.,  85.,  88.,  46.,  87.,  90.,  95., 113.,  90., 215., 200.,
        210., 193.,  88.,  90.,  95.,  nan,  48., 100., 105., 100.,  88.,
        100., 165., 175., 153., 150., 180., 170., 175., 110.,  72., 100.,
         88.,  86.,  90.,  70.,  76.,  65.,  69.,  60.,  70.,  95.,  80.,
         54.,  90.,  86., 165., 175., 150., 153., 150., 208., 155., 160.,
        190.,  97., 150., 130., 140., 150., 112.,  76.,  87.,  69.,  86.,
         92.,  97.,  80.,  88., 175., 150., 145., 137., 150., 198., 150.,
        158., 150., 215., 225., 175., 105., 100., 100.,  88.,  95.,  46.,
        150., 167., 170., 180., 100.,  88.,  72.,  94.,  90.,  85., 107.,
         90., 145., 230.,  49.,  75.,  91., 112., 150., 110., 122., 180.,
         95.,  nan, 100., 100.,  67.,  80.,  65.,  75., 100., 110., 105.,
        140., 150., 150., 140., 150., 

In [120]:
 print("Mean: ", np.nanmean(horsepower))
 print("Standard deviation:", np.nanstd(horsepower))
 print("Minimum: ", np.nanmin(horsepower))
 print("Maximum: ", np.nanmax(horsepower))


Mean:  105.0825
Standard deviation: 38.72028788309819
Minimum:  46.0
Maximum:  230.0


In [121]:
np.nanpercentile(horsepower,2)

52.0

In [122]:
import matplotlib.pyplot as plt

In [123]:
a = np.arange(5)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2 3 4]
[[0]
 [1]
 [2]]


In [124]:
a*b

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [125]:
~np.array(a>=1)

array([ True, False, False, False, False])

In [126]:
data = pd.Series(a)
data


0    0
1    1
2    2
3    3
4    4
dtype: int32

In [127]:
data.values

array([0, 1, 2, 3, 4])

In [128]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [129]:
data[1:3]

1    1
2    2
dtype: int32